# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import a2a_pb2 as proto_dot_a2a__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/a2a_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SanctumA2AServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PostContext = channel.unary_unary(
                '/sanctum.SanctumA2AService/PostContext',
                request_serializer=proto_dot_a2a__pb2.AgentPacket.SerializeToString,
                response_deserializer=proto_dot_a2a__pb2.AgentPacket.FromString,
                _registered_method=True)
        self.SecureChannel = channel.stream_stream(
                '/sanctum.SanctumA2AService/SecureChannel',
                request_serializer=proto_dot_a2a__pb2.AgentPacket.SerializeToString,
                response_deserializer=proto_dot_a2a__pb2.AgentPacket.FromString,
                _registered_method=True)


class SanctumA2AServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PostContext(self, request, context):
        """Unary call for single-shot context updates or handshakes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SecureChannel(self, request_iterator, context):
        """Bidirectional streaming for real-time secure communication
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SanctumA2AServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PostContext': grpc.unary_unary_rpc_method_handler(
                    servicer.PostContext,
                    request_deserializer=proto_dot_a2a__pb2.AgentPacket.FromString,
                    response_serializer=proto_dot_a2a__pb2.AgentPacket.SerializeToString,
            ),
            'SecureChannel': grpc.stream_stream_rpc_method_handler(
                    servicer.SecureChannel,
                    request_deserializer=proto_dot_a2a__pb2.AgentPacket.FromString,
                    response_serializer=proto_dot_a2a__pb2.AgentPacket.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sanctum.SanctumA2AService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sanctum.SanctumA2AService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SanctumA2AService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PostContext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sanctum.SanctumA2AService/PostContext',
            proto_dot_a2a__pb2.AgentPacket.SerializeToString,
            proto_dot_a2a__pb2.AgentPacket.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SecureChannel(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/sanctum.SanctumA2AService/SecureChannel',
            proto_dot_a2a__pb2.AgentPacket.SerializeToString,
            proto_dot_a2a__pb2.AgentPacket.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
