# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: a2a.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ta2a.proto\x12\x07sanctum\"\xa6\x01\n\x0b\x41gentPacket\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\'\n\thandshake\x18\x02 \x01(\x0b\x32\x12.sanctum.HandshakeH\x00\x12&\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x16.sanctum.EncryptedDataH\x00\x12\'\n\theartbeat\x18\x04 \x01(\x0b\x32\x12.sanctum.HeartbeatH\x00\x42\t\n\x07payload\"C\n\tHandshake\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x12\n\npublic_key\x18\x02 \x01(\x0c\x12\x0f\n\x07version\x18\x03 \x01(\t\"D\n\rEncryptedData\x12\x12\n\nciphertext\x18\x01 \x01(\x0c\x12\r\n\x05nonce\x18\x02 \x01(\x0c\x12\x10\n\x08\x61uth_tag\x18\x03 \x01(\x0c\"2\n\tHeartbeat\x12\x12\n\nlatency_ms\x18\x01 \x01(\x03\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x32\x93\x01\n\x11SanctumA2AService\x12;\n\x0bPostContext\x12\x14.sanctum.AgentPacket\x1a\x14.sanctum.AgentPacket\"\x00\x12\x41\n\rSecureChannel\x12\x14.sanctum.AgentPacket\x1a\x14.sanctum.AgentPacket\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'a2a_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_AGENTPACKET']._serialized_start=23
  _globals['_AGENTPACKET']._serialized_end=189
  _globals['_HANDSHAKE']._serialized_start=191
  _globals['_HANDSHAKE']._serialized_end=258
  _globals['_ENCRYPTEDDATA']._serialized_start=260
  _globals['_ENCRYPTEDDATA']._serialized_end=328
  _globals['_HEARTBEAT']._serialized_start=330
  _globals['_HEARTBEAT']._serialized_end=380
  _globals['_SANCTUMA2ASERVICE']._serialized_start=383
  _globals['_SANCTUMA2ASERVICE']._serialized_end=530
# @@protoc_insertion_point(module_scope)
