# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import a2a_pb2 as a2a__pb2


class SanctumA2AServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PostContext = channel.unary_unary(
                '/sanctum.SanctumA2AService/PostContext',
                request_serializer=a2a__pb2.AgentPacket.SerializeToString,
                response_deserializer=a2a__pb2.AgentPacket.FromString,
                )
        self.SecureChannel = channel.stream_stream(
                '/sanctum.SanctumA2AService/SecureChannel',
                request_serializer=a2a__pb2.AgentPacket.SerializeToString,
                response_deserializer=a2a__pb2.AgentPacket.FromString,
                )


class SanctumA2AServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PostContext(self, request, context):
        """Unary call for single-shot context updates or handshakes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SecureChannel(self, request_iterator, context):
        """Bidirectional streaming for real-time secure communication
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SanctumA2AServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PostContext': grpc.unary_unary_rpc_method_handler(
                    servicer.PostContext,
                    request_deserializer=a2a__pb2.AgentPacket.FromString,
                    response_serializer=a2a__pb2.AgentPacket.SerializeToString,
            ),
            'SecureChannel': grpc.stream_stream_rpc_method_handler(
                    servicer.SecureChannel,
                    request_deserializer=a2a__pb2.AgentPacket.FromString,
                    response_serializer=a2a__pb2.AgentPacket.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sanctum.SanctumA2AService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SanctumA2AService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PostContext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sanctum.SanctumA2AService/PostContext',
            a2a__pb2.AgentPacket.SerializeToString,
            a2a__pb2.AgentPacket.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SecureChannel(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/sanctum.SanctumA2AService/SecureChannel',
            a2a__pb2.AgentPacket.SerializeToString,
            a2a__pb2.AgentPacket.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
